### ISSUE TITLE
about: home: url should be http

### ISSUE THREAD

**Issue by magnunor** [conda-forge/hyperspy-feedstock#30]
In the `meta.yaml` file the url to the HyperSpy webpage is `https`. However, using this link one gets a certificate warning.

So the link should be changed from `https://hyperspy.org` to `http://hyperspy.org`.

Line: https://github.com/conda-forge/hyperspy-feedstock/blob/master/recipe/meta.yaml#L144

**Comment by francisco-dlp** [comment]
Or, an even better fix, get https for hyperspy.org ;)

**Comment by ericpre** [comment]
Done.
